from sqlalchemy import Column, Integer, String, ForeignKey, Table, Boolean, DateTime
from sqlalchemy.orm import relationship, declarative_base
from datetime import datetime
import uuid
from .database import engine

Base = declarative_base()

# Helper Table: Maps Access Groups to specific Tools/Modules
group_tool_association = Table(
    'group_tool_association', Base.metadata,
    Column('group_id', Integer, ForeignKey('access_groups.id')),
    Column('tool_id', Integer, ForeignKey('tools.id'))
)

class Tool(Base):
    """Represents the 'TheX' suite (TheLogX, TheRemoteX, etc.)"""
    __tablename__ = 'tools'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True, nullable=False) # e.g., "TheLogX"
    description = Column(String(255))

class AccessGroup(Base):
    """Permission buckets created by Masters"""
    __tablename__ = 'access_groups'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)
    master_id = Column(Integer, ForeignKey('users.id')) # The Master who created this group
    
    # Relationships
    tools = relationship("Tool", secondary=group_tool_association)
    members = relationship("User", back_populates="access_group")

class User(Base):
    """Comprehensive User model covering OEM, Master, and End-User"""
    __tablename__ = 'users'
    
    id = Column(Integer, primary_key=True)
    username = Column(String(50), unique=True, nullable=False)
    email = Column(String(100), unique=True, nullable=False)
    password_hash = Column(String(128), nullable=False)
    
    # Hierarchy Logic
    role = Column(String(20), default="USER") # OEM, MASTER, or USER
    is_active = Column(Boolean, default=True)
    
    # Linking to Access Groups
    access_group_id = Column(Integer, ForeignKey('access_groups.id'), nullable=True)
    access_group = relationship("AccessGroup", back_populates="members")

    # Tracking for OEM purposes
    created_at = Column(DateTime, default=datetime.utcnow)
    invited_by_code = Column(String(50), nullable=True)

class InviteCode(Base):
    """The Gatekeeper: Pre-authorized signup codes generated by OEM"""
    __tablename__ = 'invite_codes'
    
    id = Column(Integer, primary_key=True)
    code = Column(String(50), unique=True, default=lambda: str(uuid.uuid4())[:8].upper())
    role_to_assign = Column(String(20)) # Which role does this code grant?
    target_group_id = Column(Integer, ForeignKey('access_groups.id'), nullable=True)
    is_used = Column(Boolean, default=False)
    expires_at = Column(DateTime)
